coverage:
    range: 90..100
    round: down
    precision: 2
    status:
        project: false
        patch:
            default:
                target: 100
                threshold: 0.0
                only_pulls: true
