packages:
    - "."

allowBuilds:
    "@parcel/watcher": set this to true or false
    esbuild: set this to true or false
    pre-commit: set this to true or false
    spawn-sync: set this to true or false
    unrs-resolver: set this to true or false

onlyBuiltDependencies:
    - "."
