name: Feature request
description: Suggest an idea for this plugin.
title: "[FEAT]: "
labels: ["enhancement"]

body:
    - type: textarea
      id: problem-description
      attributes:
          label: Is your feature request related to a problem? Please describe.
          description: A clear and concise description of what the problem is.
          placeholder: I'm always frustrated when [...]
      validations:
          required: false
    - type: textarea
      id: solution-description
      attributes:
          label: Describe the solution you'd like
          description: A clear and concise description of what you want to happen.
          placeholder: I wanted that [...]
      validations:
          required: true
    - type: textarea
      id: context
      attributes:
          label: Additional context
          description: Add any other context or screenshots about the feature request here.
          placeholder: Explain any additional context [...]
      validations:
          required: false
