name: Close Stale Issues & PRs

permissions:
    contents: write
    issues: write
    pull-requests: write

on:
    workflow_dispatch:
    schedule:
        - cron: "0 4 * * 0"

jobs:
    stale:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/stale@v4.1.1
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  days-before-issue-stale: 365
                  days-before-issue-close: 30
                  days-before-pr-stale: 365
                  days-before-pr-close: 30
                  stale-issue-label: "stale"
                  stale-pr-label: "stale"
                  operations-per-run: 256
                  delete-branch: true
