name: Lint and Test Code

on:
    pull_request:
        branches-ignore: [gh-pages]
    push:
        branches-ignore: [gh-pages]

jobs:
    lint_and_test_code:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v6

            - name: Setup Node
              uses: actions/setup-node@v6
              with:
                  node-version: "24"
                  cache: "npm"

            - name: Install dependencies
              run: npm ci

            - name: Lint
              run: npm run lint || (echo && echo "Run 'npm run format' to fix." && exit 1)

            - name: Test
              run: npm run test

            - name: Upload results to Codecov
              uses: codecov/codecov-action@v6
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
