name: Lint and Test

on:
    pull_request:
        branches: [master]

env:
    COREPACK_ENABLE_STRICT: 0

jobs:
    lint_and_test:
        runs-on: ubuntu-latest

        steps:
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: "20"

            - uses: actions/checkout@v3

            - name: Install Dependencies
              run: npm install -g pnpm && pnpm install

            - name: Lint
              run: pnpm lint

            - name: Test
              run: pnpm test
